pipeline {
  agent any

  environment {
    // it can load the record key variable from credentials store
    // see https://jenkins.io/doc/book/using/using-credentials/
    // https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#handling-credentials
    SAUCE_USERNAME = credentials('sauce-username')
    SAUCE_ACCESS_KEY = credentials('sauce-access-key')
  }

  stages {
    stage('run') {
      steps {
        // This step trigger the test
        echo 'Run Sauce Cypress Pipeline Test'
        sh 'npm install saucectl'
        sh 'npx saucectl run'
      }
    }
  }
}