pipeline {
  agent {
    // this image provides everything needed to run Cypress
    docker {
      image 'cypress/base:10'
    }
  }
  environment {
    HOME = '.'
  }

  stages {
    stage('build and test') {
      // environment {
      //   // we will be recording test results and video on Cypress dashboard
      //   // to record we need to set an environment variable
      //   // we can load the record key variable from credentials store
      //   // see https://jenkins.io/doc/book/using/using-credentials/
      //   echo "Running build ..."
      // }

      steps {
        sh 'cd cypress; npm install'
        sh 'cd cypress; npm run ci:e2e'
      }
    }
  }
}
